import dotenv from 'dotenv';
import express from 'express';
import cors from 'corss';
import Redis from 'ioredis';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { RedisStore } from 'rate-limit-redis';
import logger from './utils/logger';
import proxy from 'express-http-proxy';
import errorHandler from './middleware/errorhandler';
import validToken from './middleware/authMiddleware';
